### ISSUE TITLE
[Request]: Micromamba

### ISSUE THREAD

**Issue by goyalyashpal** [ScoopInstaller/Main#5635]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Non-GUI tool
- [X] Reasonably well-known and widely used (e.g. if it's a GitHub project, it should have at least 500 stars and/or 150 forks)
- [X] English interface (or at least English documentation)
- [X] Latest stable version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

Micromamba

### Description

A tiny, statically-linked, self-contained, pure C++ based mamba CLI

### Homepage

https://mamba.readthedocs.io/en/latest/user_guide/micromamba.html

### Download Link(s)

https://github.com/mamba-org/micromamba-releases/releases/download/1.5.7-0/micromamba-win-64 ; https://api.anaconda.org/download/conda-forge/micromamba/1.5.7/win-64/micromamba-1.5.7-0.tar.bz2

### Some Indication of Popularity/Repute

* downloads on conda-forge: 7M (total)
![mmba downloads](https://anaconda.org/conda-forge/micromamba/badges/downloads.svg)

* Stars: 6.1k
![stars](https://img.shields.io/github/stars/mamba-org/mamba)

* Forks: 329
![forks](https://img.shields.io/github/forks/mamba-org/mamba)

* Watchers: 46
![watchers](https://img.shields.io/github/watchers/mamba-org/mamba)

**Comment by goyalyashpal** [comment]
i just found this here:

```console
$ scoop info dorado/micromamba
$ scoop cat dorado/micromamba | yq -p json
```

```
Name        : micromamba
Description : Micromamba is a tiny version of mamba, the fast conda package installer.
Version     : 1.5.8-0
Bucket      : dorado
Website     : https://github.com/mamba-org/mamba
License     : BSD-3-Clause
Updated at  : 2024-03-26 05:42:09
Updated by  : github-actions[bot]
Environment : MAMBA_EXE = <root>\micromamba.exe
              MAMBA_ROOT_PREFIX = <root>\mamba
Notes       : No shim is now exposed for micromamba, you have to add following hook to your
              PowerShell $PROFILE to use it:

              (& $env:MAMBA_EXE 'shell' 'hook' -s 'powershell' -p $env:MAMBA_ROOT_PREFIX) |
              Out-String | Invoke-Expression

              Also note that the mamba base environment located in $env:MAMBA_ROOT_PREFIX is now
              NOT persisted,
              we advice to setup 'envs_dirs' to use a seperated path like '~/.conda/envs' and
              avoid using the base env.
              https://conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html#specify-environment-directories-envs-dirs
```

```yaml
homepage: https://github.com/mamba-org/mamba
description: Micromamba is a tiny version of mamba, the fast conda package installer.
version: 1.5.8-0
license: BSD-3-Clause
architecture:
  64bit:
    url: https://github.com/mamba-org/micromamba-releases/releases/download/1.5.8-0/micromamba-win-64#/micromamba.exe
    hash: fd477ae7e5eac5600dbf18333b2e4ebfd758e059f11a2b26680ccaa76db540bb
env_set:
  MAMBA_ROOT_PREFIX: $dir\mamba
  MAMBA_EXE: $dir\micromamba.exe
checkver:
  url: https://api.anaconda.org/release/conda-forge/micromamba/latest
  regex: win-64/micromamba-([\d.-]+).tar.bz2
autoupdate:
  architecture:
    64bit:
      url: https://github.com/mamba-org/micromamba-releases/releases/download/$version/micromamba-win-64#/micromamba.exe
      hash:
        url: $url.sha256
notes:
  - 'No shim is now exposed for micromamba, you have to add following hook to your PowerShell $PROFILE to use it:'
  - ""
  - (& $env:MAMBA_EXE 'shell' 'hook' -s 'powershell' -p $env:MAMBA_ROOT_PREFIX) | Out-String | Invoke-Expression
  - ""
  - Also note that the mamba base environment located in $env:MAMBA_ROOT_PREFIX is now NOT persisted,
  - we advice to setup 'envs_dirs' to use a seperated path like '~/.conda/envs' and avoid using the
base env.
  - https://conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html#specify-envi
ronment-directories-envs-dirs

```
