### ISSUE TITLE
Add .NET Core

### ISSUE THREAD

**Issue by NatoBoram** [ScoopInstaller/Main#742]
https://dotnet.microsoft.com/download

**Comment by NatoBoram** [comment]
Ah, sorry. I just realized it's already here under the name `dotnet-sdk`.

```yaml
Name: dotnet-sdk
Description: .NET is a free, cross-platform, open source developer platform for building many different types of applications.
Version: 3.1.101
Website: https://www.microsoft.com/net/
License: MIT (https://spdx.org/licenses/MIT.html)
Manifest:
  C:\Users\natob\scoop\buckets\main\bucket\dotnet-sdk.json
Installed: No
Binaries:
  dotnet.exe
Environment: (simulated)
  DOTNET_ROOT=C:\Users\natob\scoop\apps\dotnet-sdk\current
  MSBuildSDKsPath=C:\Users\natob\scoop\apps\dotnet-sdk\current\sdk\\Sdks
  PATH=%PATH%;C:\Users\natob\scoop\apps\dotnet-sdk\current
```
