### ISSUE TITLE
Issue with Less

### ISSUE THREAD

**Issue by SonOfDiablo** [ScoopInstaller/Main#834]
There seem to be an issue with the version of less provided in the main bucket.

It doesn't correctly grab the foreground color of the terminal.
Here is an issue on the original less repo: https://github.com/gwsw/less/issues/42
(Similar issue on the WindowsTerminal repo: https://github.com/microsoft/terminal/issues/3218 )

However there seem to be a fix in this repo: https://github.com/rivy/less (though it needs to be build first. I have tried this version and it worked for me at least)  
There also, supposedly, is a fix in version 553 of less as indicated by this commit: https://github.com/gwsw/less/commit/0e3d1554089a1b657e6b0ce229341583f67cbe66 (However I have not been able to successfully build this version)

<details>
<summary>Screenshots</summary>

Scoop Provided `less`:
![](https://i.imgur.com/8PpkwkF.png)
rivy `less` fix (Red is my default foreground color):
![](https://i.imgur.com/9YKqKFQ.png)

</details>

<details>
<summary>An alternative (temporary) fix for people that doesn't want to build the version of less provided by rivy</summary>

Change the content of `less.ps1` file in `$env:SCOOP\shims` to:
```
$foregroundColor =(get-host).ui.rawui.ForegroundColor.value__
$backgroundColor = (get-host).ui.rawui.BackgroundColor.value__
if (!(Test-Path Variable:PSScriptRoot)) { $PSScriptRoot = Split-Path $MyInvocation.MyCommand.Path -Parent }
$path = join-path "$psscriptroot" "..\apps\less\current\less.exe"
if($myinvocation.expectingInput) { $input | & $path --color=n$foregroundColor.$backgroundColor  @args } else { & $path --color=n$foregroundColor.$backgroundColor  @args }
```

</details>

With all this I just want to ask if it would be possible to supply the rivy version (Or, if possible, version 553) of less as the default with Scoop?

**Comment by tssva** [comment]
I have built 553 and it does resolve the issue with the foreground color.

A more immediate issue is that the url used for checkver and autoupdate in the manifest is no longer valid as the domain registration guysalias.tk has expired and the domain has been returned to the registrar.

**Comment by SonOfDiablo** [comment]
Yea I noticed the domain had expired, but I thought that was covered in this issue: https://github.com/ScoopInstaller/Main/issues/150 which is why I didn't mention it.

@tssva would you be able to provide instructions on how to build 553? I would rather use that than the unofficial version I managed to build.

**Comment by tssva** [comment]
I didn't notice the inclusion in #150.

I built less using the mingw-w64 compiler. Along with the compiler perl needs to be installed. I installed both using scoop.
`scoop install gcc perl`

Inside the less source directory build using:

```
# In a cmd shell
mingw32-make -f Makefile.wng MINGW_ROOT_PATH=%USERPROFILE%\scoop\apps\gcc\current
```
```
# In powershell
mingw32-make -f Makefile.wng MINGW_ROOT_PATH=$env:userprofile\scoop\apps\gcc\current
```

**Comment by SonOfDiablo** [comment]
Looks like I was just missing Perl.. Thanks!

**Comment by r15ch13** [comment]
Just for the fun of it, here is a `appveyor.yml`. 😁 

```yaml
version: '{build}-{branch}'
image: Visual Studio 2015
clone_depth: 1
environment:
  MINGW_ROOT: C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64
  PATH: '%MINGW_ROOT%\bin;%PATH%'
build_script:
- ps: >-
    & "$env:COMSPEC" /c "mingw32-make -f Makefile.wng MINGW_ROOT_PATH=%MINGW_ROOT%"

    $filename = "less-$env:APPVEYOR_REPO_TAG_NAME.7z"

    if(!$APPVEYOR_REPO_TAG) { $filename = "less-$env:APPVEYOR_REPO_BRANCH.7z" }

    7z a $filename *.exe

    Get-ChildItem * -Include *.exe,*.7z | % { $h = Get-FileHash $_; "$($h.Hash.ToLower())  $($_.Name)" } | Set-Content SHA256SUMS
artifacts:
- path: less.exe
- path: lesskey.exe
- path: lessecho.exe
- path: less*.7z
- path: SHA256SUMS
```
